name: Automated JIRA API tests using Postman CLI and Newman

on:
  push:  # Se ejecuta en cada push
    branches:
      - main
  workflow_dispatch: {}  # Para ejecución manual
  schedule:
    - cron: '0 0 * * 0'  # Se ejecuta todos los domingos a medianoche

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Download Postman collection using Postman API
        run: |
          curl --location --request GET "https://api.getpostman.com/collections/39223574-3673c412-1972-4c82-a5f5-4e3c511651e6" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          --output collection.json

      - name: Download Postman environment using Postman API
        run: |
          curl --location --request GET "https://api.getpostman.com/environments/39223574-a9203bb6-7e94-4b4c-a7c5-eba45fba6c83" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          --output environment.json

      - name: Run API tests with Newman and generate HTML report
        run: |
          newman run collection.json -e environment.json --reporters cli,html --reporter-html-export report.html

      - name: Configure Git for deployment
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Upload HTML report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: report.html

      - name: Upload Postman collection as artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-collection
          path: collection.json
